# Generated by Django 6.0.1 on 2026-01-14 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('department', models.CharField(blank=True, max_length=80)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('doj', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
